
// @ts-check
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
      items: ['core-concepts/how-it-works','core-concepts/architecture'],
      collapsed: false,
      items: ['developer-guide/go','developer-guide/rust','developer-guide/typescript'],
    },
    'faq',
    'rest-api',
    'roadmap',
  ],
};